import 'dotenv/config'
import { prisma } from '../src/lib/prisma'
import { TempleStatus } from '@prisma/client'

// Comprehensive list of Utah temples based on official Church data
const utahTemples = [
  {
    name: "Salt Lake Temple",
    slug: "salt-lake-temple",
    country: "United States",
    state: "Utah",
    city: "Salt Lake City",
    address: "50 W North Temple St, Salt Lake City, UT 84150",
    announcementDate: new Date("1853-02-14"),
    groundbreakingDate: new Date("1853-04-06"),
    dedicationDate: new Date("1893-04-06"),
    siteSize: "10 acres",
    exteriorFinish: "Quartz monzonite granite",
    totalFloorArea: "253,015 sq ft",
    instructionRooms: 10,
    sealingRooms: 15,
    baptistry: true,
    spires: 6,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: true,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.RENOVATING
  },
  {
    name: "St. George Utah Temple",
    slug: "st-george-utah-temple",
    country: "United States",
    state: "Utah",
    city: "St. George",
    address: "250 E 400 S, St. George, UT 84770",
    announcementDate: new Date("1871-11-09"),
    groundbreakingDate: new Date("1871-11-09"),
    dedicationDate: new Date("1877-04-06"),
    siteSize: "9.27 acres",
    exteriorFinish: "Red sandstone",
    totalFloorArea: "110,000 sq ft",
    instructionRooms: 6,
    sealingRooms: 14,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Logan Utah Temple",
    slug: "logan-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Logan",
    address: "175 N 300 E, Logan, UT 84321",
    announcementDate: new Date("1877-05-18"),
    groundbreakingDate: new Date("1877-05-17"),
    dedicationDate: new Date("1884-05-17"),
    siteSize: "9.09 acres",
    exteriorFinish: "Limestone",
    totalFloorArea: "119,619 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 2,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Manti Utah Temple",
    slug: "manti-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Manti",
    address: "100 N Main St, Manti, UT 84642",
    announcementDate: new Date("1877-04-25"),
    groundbreakingDate: new Date("1877-04-25"),
    dedicationDate: new Date("1888-05-21"),
    siteSize: "13.8 acres",
    exteriorFinish: "Oolite limestone",
    totalFloorArea: "100,373 sq ft",
    instructionRooms: 6,
    sealingRooms: 11,
    baptistry: true,
    spires: 2,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Ogden Utah Temple",
    slug: "ogden-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Ogden",
    address: "350 22nd St, Ogden, UT 84401",
    announcementDate: new Date("1967-08-26"),
    groundbreakingDate: new Date("1970-09-08"),
    dedicationDate: new Date("1972-01-18"),
    siteSize: "11.6 acres",
    exteriorFinish: "Cast stone",
    totalFloorArea: "115,000 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 2,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Provo Utah Rock Canyon Temple",
    slug: "provo-utah-rock-canyon-temple",
    country: "United States",
    state: "Utah",
    city: "Provo",
    address: "2200 Temple Hill Dr, Provo, UT 84604",
    announcementDate: new Date("1967-08-26"),
    groundbreakingDate: new Date("1970-09-15"),
    dedicationDate: new Date("1972-02-09"),
    siteSize: "17 acres",
    exteriorFinish: "Cast stone",
    totalFloorArea: "128,325 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Jordan River Utah Temple",
    slug: "jordan-river-utah-temple",
    country: "United States",
    state: "Utah",
    city: "South Jordan",
    address: "10200 S 1300 W, South Jordan, UT 84095",
    announcementDate: new Date("1978-04-01"),
    groundbreakingDate: new Date("1979-01-27"),
    dedicationDate: new Date("1981-11-16"),
    siteSize: "28.2 acres",
    exteriorFinish: "Reinforced concrete and marble chips",
    totalFloorArea: "148,236 sq ft",
    instructionRooms: 10,
    sealingRooms: 18,
    baptistry: true,
    spires: 2,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Bountiful Utah Temple",
    slug: "bountiful-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Bountiful",
    address: "640 S Bountiful Blvd, Bountiful, UT 84010",
    announcementDate: new Date("1992-10-03"),
    groundbreakingDate: new Date("1993-05-08"),
    dedicationDate: new Date("1995-01-08"),
    siteSize: "12 acres",
    exteriorFinish: "Reinforced concrete with marble chips",
    totalFloorArea: "104,000 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Mount Timpanogos Utah Temple",
    slug: "mount-timpanogos-utah-temple",
    country: "United States",
    state: "Utah",
    city: "American Fork",
    address: "742 N 900 E, American Fork, UT 84003",
    announcementDate: new Date("1992-10-03"),
    groundbreakingDate: new Date("1994-10-09"),
    dedicationDate: new Date("1996-10-13"),
    siteSize: "15.6 acres",
    exteriorFinish: "Reinforced concrete with marble chips",
    totalFloorArea: "107,240 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Vernal Utah Temple",
    slug: "vernal-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Vernal",
    address: "1750 1500 S, Vernal, UT 84078",
    announcementDate: new Date("1994-04-02"),
    groundbreakingDate: new Date("1995-11-04"),
    dedicationDate: new Date("1997-11-02"),
    siteSize: "10.2 acres",
    exteriorFinish: "Reinforced concrete with marble chips",
    totalFloorArea: "38,771 sq ft",
    instructionRooms: 2,
    sealingRooms: 3,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Monticello Utah Temple",
    slug: "monticello-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Monticello",
    address: "655 S 500 E, Monticello, UT 84535",
    announcementDate: new Date("1995-04-01"),
    groundbreakingDate: new Date("1996-07-20"),
    dedicationDate: new Date("1998-07-26"),
    siteSize: "10 acres",
    exteriorFinish: "Reinforced concrete with marble chips",
    totalFloorArea: "39,398 sq ft",
    instructionRooms: 2,
    sealingRooms: 3,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Draper Utah Temple",
    slug: "draper-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Draper",
    address: "14065 S Bangerter Pkwy, Draper, UT 84020",
    announcementDate: new Date("2004-04-03"),
    groundbreakingDate: new Date("2006-08-05"),
    dedicationDate: new Date("2009-03-20"),
    siteSize: "28 acres",
    exteriorFinish: "Granite and cast stone",
    totalFloorArea: "57,000 sq ft",
    instructionRooms: 4,
    sealingRooms: 7,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Oquirrh Mountain Utah Temple",
    slug: "oquirrh-mountain-utah-temple",
    country: "United States",
    state: "Utah",
    city: "South Jordan",
    address: "11022 S 4000 W, South Jordan, UT 84009",
    announcementDate: new Date("2005-04-02"),
    groundbreakingDate: new Date("2006-12-16"),
    dedicationDate: new Date("2009-08-21"),
    siteSize: "11 acres",
    exteriorFinish: "Light gray granite",
    totalFloorArea: "60,000 sq ft",
    instructionRooms: 4,
    sealingRooms: 8,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Payson Utah Temple",
    slug: "payson-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Payson",
    address: "15 W 200 S, Payson, UT 84651",
    announcementDate: new Date("2008-10-04"),
    groundbreakingDate: new Date("2011-10-08"),
    dedicationDate: new Date("2015-06-07"),
    siteSize: "15.53 acres",
    exteriorFinish: "Natural granite and pre-cast concrete",
    totalFloorArea: "96,630 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Provo City Center Temple",
    slug: "provo-city-center-temple",
    country: "United States",
    state: "Utah",
    city: "Provo",
    address: "50 S University Ave, Provo, UT 84601",
    announcementDate: new Date("2011-10-01"),
    groundbreakingDate: new Date("2011-05-12"),
    dedicationDate: new Date("2016-03-20"),
    siteSize: "3.4 acres",
    exteriorFinish: "Natural stone and stucco",
    totalFloorArea: "85,084 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: true,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Cedar City Utah Temple",
    slug: "cedar-city-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Cedar City",
    address: "1620 W Royal Hunte Dr, Cedar City, UT 84720",
    announcementDate: new Date("2017-04-01"),
    groundbreakingDate: new Date("2017-04-15"),
    dedicationDate: new Date("2017-12-10"),
    siteSize: "9.39 acres",
    exteriorFinish: "Natural stone",
    totalFloorArea: "42,657 sq ft",
    instructionRooms: 3,
    sealingRooms: 6,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Saratoga Springs Utah Temple",
    slug: "saratoga-springs-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Saratoga Springs",
    address: "1125 N Temple Dr, Saratoga Springs, UT 84045",
    announcementDate: new Date("2017-04-01"),
    groundbreakingDate: new Date("2019-10-12"),
    dedicationDate: new Date("2023-12-17"),
    siteSize: "15.6 acres",
    exteriorFinish: "Natural stone",
    totalFloorArea: "87,000 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Layton Utah Temple",
    slug: "layton-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Layton",
    address: "1750 N 1800 E, Layton, UT 84040",
    announcementDate: new Date("2018-04-07"),
    groundbreakingDate: new Date("2020-05-23"),
    dedicationDate: new Date("2023-10-15"),
    siteSize: "15.79 acres",
    exteriorFinish: "Natural stone",
    totalFloorArea: "87,000 sq ft",
    instructionRooms: 6,
    sealingRooms: 12,
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.DEDICATED
  },
  {
    name: "Orem Utah Temple",
    slug: "orem-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Orem",
    address: "1471 S Geneva Rd, Orem, UT 84097",
    announcementDate: new Date("2018-04-07"),
    groundbreakingDate: new Date("2022-05-21"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.UNDER_CONSTRUCTION
  },
  {
    name: "Syracuse Utah Temple",
    slug: "syracuse-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Syracuse",
    address: "4450 W 1700 S, Syracuse, UT 84075",
    announcementDate: new Date("2020-04-05"),
    groundbreakingDate: new Date("2022-06-04"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.UNDER_CONSTRUCTION
  },
  {
    name: "Smithfield Utah Temple",
    slug: "smithfield-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Smithfield",
    address: "700 S 250 W, Smithfield, UT 84335",
    announcementDate: new Date("2021-10-03"),
    groundbreakingDate: new Date("2023-05-06"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.UNDER_CONSTRUCTION
  },
  {
    name: "Brigham City Utah Temple",
    slug: "brigham-city-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Brigham City",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "Ephraim Utah Temple",
    slug: "ephraim-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Ephraim",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "Lindon Utah Temple",
    slug: "lindon-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Lindon",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "Taylorsville Utah Temple",
    slug: "taylorsville-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Taylorsville",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "West Jordan Utah Temple",
    slug: "west-jordan-utah-temple",
    country: "United States",
    state: "Utah",
    city: "West Jordan",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "Deseret Peak Utah Temple",
    slug: "deseret-peak-utah-temple",
    country: "United States",
    state: "Utah",
    city: "Tooele",
    announcementDate: new Date("2021-10-03"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.ANNOUNCED
  },
  {
    name: "Red Cliffs Utah Temple",
    slug: "red-cliffs-utah-temple",
    country: "United States",
    state: "Utah",
    city: "St. George",
    announcementDate: new Date("2021-10-03"),
    groundbreakingDate: new Date("2022-11-05"),
    baptistry: true,
    spires: 1,
    angelMoroni: true,
    visitorsCenter: false,
    arrivalCenter: false,
    patronHousing: false,
    distributionCenter: false,
    status: TempleStatus.UNDER_CONSTRUCTION
  }
]

async function main() {
  console.log('🌟 Starting Utah temple seeding...')

  let seeded = 0
  let updated = 0

  for (const templeData of utahTemples) {
    try {
      const result = await prisma.temple.upsert({
        where: { slug: templeData.slug },
        update: templeData,
        create: templeData,
      })

      const existing = await prisma.temple.findUnique({
        where: { slug: templeData.slug }
      })

      if (existing) {
        updated++
        console.log(`✅ Updated temple: ${result.name}`)
      } else {
        seeded++
        console.log(`✅ Seeded new temple: ${result.name}`)
      }
    } catch (error) {
      console.error(`❌ Error seeding temple ${templeData.name}:`, error)
    }
  }

  console.log(`\n📊 Summary:`)
  console.log(`   🆕 New temples seeded: ${seeded}`)
  console.log(`   📝 Existing temples updated: ${updated}`)
  console.log(`   🏛️  Total Utah temples: ${utahTemples.length}`)
  console.log('🎉 Utah temple seeding completed!')
}

main()
  .catch((e) => {
    console.error('💥 Error during seeding:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })